// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ObligatorioApiario.Data;

#nullable disable

namespace ObligatorioApiario.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260705233230_AddBarrilEstado")]
    partial class AddBarrilEstado
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ObligatorioApiario.Models.Apiario", b =>
                {
                    b.Property<int>("ID_Apiario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID_Apiario"));

                    b.Property<int>("Cant_Colmenas")
                        .HasColumnType("integer");

                    b.Property<decimal>("Latitud")
                        .HasColumnType("decimal(9,6)");

                    b.Property<decimal>("Longitud")
                        .HasColumnType("decimal(9,6)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notas")
                        .HasColumnType("text");

                    b.Property<string>("Ubicacion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Zona")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID_Apiario");

                    b.ToTable("Apiarios");
                });

            modelBuilder.Entity("ObligatorioApiario.Models.Apicultor", b =>
                {
                    b.Property<int>("CIApicultor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CIApicultor"));

                    b.Property<string>("Cargo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CIApicultor");

                    b.ToTable("Apicultores", t =>
                        {
                            t.HasCheckConstraint("CHK_Apicultor_Cargo", "\"Cargo\" IN ('Administrador de Apiario', 'Apicultor de Campo')");
                        });
                });

            modelBuilder.Entity("ObligatorioApiario.Models.ApicultorTelefono", b =>
                {
                    b.Property<int>("CIApicultor")
                        .HasColumnType("integer");

                    b.Property<int>("Telefono")
                        .HasColumnType("integer");

                    b.HasKey("CIApicultor", "Telefono");

                    b.ToTable("ApicultorTelefonos");
                });

            modelBuilder.Entity("ObligatorioApiario.Models.Aplica", b =>
                {
                    b.Property<int>("ID_Colmena")
                        .HasColumnType("integer");

                    b.Property<int>("ID_Tratamiento")
                        .HasColumnType("integer");

                    b.HasKey("ID_Colmena", "ID_Tratamiento");

                    b.HasIndex("ID_Tratamiento");

                    b.ToTable("Aplica");
                });

            modelBuilder.Entity("ObligatorioApiario.Models.Aporta", b =>
                {
                    b.Property<int>("ID_Aporte")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID_Aporte"));

                    b.Property<int>("ID_Barril")
                        .HasColumnType("integer");

                    b.Property<int>("ID_Colmena")
                        .HasColumnType("integer");

                    b.Property<int>("ID_Cosecha")
                        .HasColumnType("integer");

                    b.Property<decimal>("Kilos")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("ID_Aporte");

                    b.HasIndex("ID_Barril");

                    b.HasIndex("ID_Colmena");

                    b.HasIndex("ID_Cosecha");

                    b.ToTable("Aporta");
                });

            modelBuilder.Entity("ObligatorioApiario.Models.Asigna", b =>
                {
                    b.Property<int>("ID_Colmena")
                        .HasColumnType("integer");

                    b.Property<int>("ID_Reina")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Fecha_Asignacion")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ID_Colmena", "ID_Reina");

                    b.HasIndex("ID_Reina");

                    b.ToTable("Asigna");
                });

            modelBuilder.Entity("ObligatorioApiario.Models.Barril", b =>
                {
                    b.Property<int>("ID_Barril")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID_Barril"));

                    b.Property<int>("CIApicultor")
                        .HasColumnType("integer");

                    b.Property<decimal>("Cantidad_Miel")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("ID_Barril");

                    b.HasIndex("CIApicultor");

                    b.ToTable("Barriles");
                });

            modelBuilder.Entity("ObligatorioApiario.Models.Colmena", b =>
                {
                    b.Property<int>("ID_Colmena")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID_Colmena"));

                    b.Property<int>("Cant_Abejas_Estimada")
                        .HasColumnType("integer");

                    b.Property<int>("Cant_Bastidores")
                        .HasColumnType("integer");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Fortaleza_Abejas")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Identificador")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID_Colmena");

                    b.ToTable("Colmenas", t =>
                        {
                            t.HasCheckConstraint("CHK_Fortaleza_Abejas", "\"Fortaleza_Abejas\" IN ('Fuerte', 'Media', 'Débil')");
                        });
                });

            modelBuilder.Entity("ObligatorioApiario.Models.Cosecha", b =>
                {
                    b.Property<int>("ID_Cosecha")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID_Cosecha"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Identificador")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Observaciones")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID_Cosecha");

                    b.ToTable("Cosechas");
                });

            modelBuilder.Entity("ObligatorioApiario.Models.Genera", b =>
                {
                    b.Property<int>("ID_Barril")
                        .HasColumnType("integer");

                    b.Property<int>("ID_Cosecha")
                        .HasColumnType("integer");

                    b.HasKey("ID_Barril", "ID_Cosecha");

                    b.HasIndex("ID_Cosecha");

                    b.ToTable("Genera");
                });

            modelBuilder.Entity("ObligatorioApiario.Models.Herramienta", b =>
                {
                    b.Property<int>("ID_Herramienta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID_Herramienta"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID_Herramienta");

                    b.ToTable("Herramientas");
                });

            modelBuilder.Entity("ObligatorioApiario.Models.Planifica", b =>
                {
                    b.Property<int>("ID_Visita")
                        .HasColumnType("integer");

                    b.Property<int>("ID_Herramienta")
                        .HasColumnType("integer");

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer");

                    b.HasKey("ID_Visita", "ID_Herramienta");

                    b.HasIndex("ID_Herramienta");

                    b.ToTable("Planifica");
                });

            modelBuilder.Entity("ObligatorioApiario.Models.Realiza", b =>
                {
                    b.Property<int>("ID_Cosecha")
                        .HasColumnType("integer");

                    b.Property<int>("ID_Apiario")
                        .HasColumnType("integer");

                    b.Property<int>("Cant_Barriles")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Fecha_Cosecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Tipo_Miel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID_Cosecha", "ID_Apiario");

                    b.HasIndex("ID_Apiario");

                    b.ToTable("Realiza");
                });

            modelBuilder.Entity("ObligatorioApiario.Models.Reina", b =>
                {
                    b.Property<int>("ID_Reina")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID_Reina"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Identificador")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nivel_Prod")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID_Reina");

                    b.ToTable("Reinas");
                });

            modelBuilder.Entity("ObligatorioApiario.Models.Revisa", b =>
                {
                    b.Property<int>("ID_Visita")
                        .HasColumnType("integer");

                    b.Property<int>("ID_Apiario")
                        .HasColumnType("integer");

                    b.Property<string>("Clima")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<TimeSpan>("H_Llegada")
                        .HasColumnType("interval");

                    b.Property<TimeSpan>("H_Salida")
                        .HasColumnType("interval");

                    b.HasKey("ID_Visita", "ID_Apiario");

                    b.HasIndex("ID_Apiario");

                    b.ToTable("Revisa");
                });

            modelBuilder.Entity("ObligatorioApiario.Models.Tiene", b =>
                {
                    b.Property<int>("ID_Apiario")
                        .HasColumnType("integer");

                    b.Property<int>("ID_Colmena")
                        .HasColumnType("integer");

                    b.Property<string>("Columna")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Fecha_Instalacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Fila")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Sector")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID_Apiario", "ID_Colmena");

                    b.HasIndex("ID_Colmena");

                    b.ToTable("Tiene");
                });

            modelBuilder.Entity("ObligatorioApiario.Models.Tratamiento", b =>
                {
                    b.Property<int>("ID_Tratamiento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID_Tratamiento"));

                    b.Property<int>("Cant_Dosis")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Fecha_Inicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Observaciones")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID_Tratamiento");

                    b.ToTable("Tratamientos");
                });

            modelBuilder.Entity("ObligatorioApiario.Models.Visita", b =>
                {
                    b.Property<int>("ID_Visita")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID_Visita"));

                    b.Property<int>("CIApicultor")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Observaciones")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Temporada")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID_Visita");

                    b.HasIndex("CIApicultor");

                    b.ToTable("Visitas");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ObligatorioApiario.Models.ApicultorTelefono", b =>
                {
                    b.HasOne("ObligatorioApiario.Models.Apicultor", "Apicultor")
                        .WithMany("Telefonos")
                        .HasForeignKey("CIApicultor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Apicultor");
                });

            modelBuilder.Entity("ObligatorioApiario.Models.Aplica", b =>
                {
                    b.HasOne("ObligatorioApiario.Models.Colmena", "Colmena")
                        .WithMany("TratamientosAplicados")
                        .HasForeignKey("ID_Colmena")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ObligatorioApiario.Models.Tratamiento", "Tratamiento")
                        .WithMany("Aplicaciones")
                        .HasForeignKey("ID_Tratamiento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Colmena");

                    b.Navigation("Tratamiento");
                });

            modelBuilder.Entity("ObligatorioApiario.Models.Aporta", b =>
                {
                    b.HasOne("ObligatorioApiario.Models.Barril", "Barril")
                        .WithMany()
                        .HasForeignKey("ID_Barril")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ObligatorioApiario.Models.Colmena", "Colmena")
                        .WithMany()
                        .HasForeignKey("ID_Colmena")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ObligatorioApiario.Models.Cosecha", "Cosecha")
                        .WithMany()
                        .HasForeignKey("ID_Cosecha")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Barril");

                    b.Navigation("Colmena");

                    b.Navigation("Cosecha");
                });

            modelBuilder.Entity("ObligatorioApiario.Models.Asigna", b =>
                {
                    b.HasOne("ObligatorioApiario.Models.Colmena", "Colmena")
                        .WithMany("ReinasAsignadas")
                        .HasForeignKey("ID_Colmena")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ObligatorioApiario.Models.Reina", "Reina")
                        .WithMany("ColmenasAsignadas")
                        .HasForeignKey("ID_Reina")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Colmena");

                    b.Navigation("Reina");
                });

            modelBuilder.Entity("ObligatorioApiario.Models.Barril", b =>
                {
                    b.HasOne("ObligatorioApiario.Models.Apicultor", "Apicultor")
                        .WithMany("Barriles")
                        .HasForeignKey("CIApicultor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Apicultor");
                });

            modelBuilder.Entity("ObligatorioApiario.Models.Genera", b =>
                {
                    b.HasOne("ObligatorioApiario.Models.Barril", "Barril")
                        .WithMany("GeneradoPor")
                        .HasForeignKey("ID_Barril")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ObligatorioApiario.Models.Cosecha", "Cosecha")
                        .WithMany("GeneraBarriles")
                        .HasForeignKey("ID_Cosecha")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Barril");

                    b.Navigation("Cosecha");
                });

            modelBuilder.Entity("ObligatorioApiario.Models.Planifica", b =>
                {
                    b.HasOne("ObligatorioApiario.Models.Herramienta", "Herramienta")
                        .WithMany("PlanificadasEn")
                        .HasForeignKey("ID_Herramienta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ObligatorioApiario.Models.Visita", "Visita")
                        .WithMany("HerramientasPlanificadas")
                        .HasForeignKey("ID_Visita")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Herramienta");

                    b.Navigation("Visita");
                });

            modelBuilder.Entity("ObligatorioApiario.Models.Realiza", b =>
                {
                    b.HasOne("ObligatorioApiario.Models.Apiario", "Apiario")
                        .WithMany("CosechasRealizadas")
                        .HasForeignKey("ID_Apiario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ObligatorioApiario.Models.Cosecha", "Cosecha")
                        .WithMany("RealizadaEn")
                        .HasForeignKey("ID_Cosecha")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Apiario");

                    b.Navigation("Cosecha");
                });

            modelBuilder.Entity("ObligatorioApiario.Models.Revisa", b =>
                {
                    b.HasOne("ObligatorioApiario.Models.Apiario", "Apiario")
                        .WithMany("VisitasRecibidas")
                        .HasForeignKey("ID_Apiario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ObligatorioApiario.Models.Visita", "Visita")
                        .WithMany("ApiariosRevisados")
                        .HasForeignKey("ID_Visita")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Apiario");

                    b.Navigation("Visita");
                });

            modelBuilder.Entity("ObligatorioApiario.Models.Tiene", b =>
                {
                    b.HasOne("ObligatorioApiario.Models.Apiario", "Apiario")
                        .WithMany("ColmenasInstaladas")
                        .HasForeignKey("ID_Apiario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ObligatorioApiario.Models.Colmena", "Colmena")
                        .WithMany("Instalaciones")
                        .HasForeignKey("ID_Colmena")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Apiario");

                    b.Navigation("Colmena");
                });

            modelBuilder.Entity("ObligatorioApiario.Models.Visita", b =>
                {
                    b.HasOne("ObligatorioApiario.Models.Apicultor", "Apicultor")
                        .WithMany("Visitas")
                        .HasForeignKey("CIApicultor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Apicultor");
                });

            modelBuilder.Entity("ObligatorioApiario.Models.Apiario", b =>
                {
                    b.Navigation("ColmenasInstaladas");

                    b.Navigation("CosechasRealizadas");

                    b.Navigation("VisitasRecibidas");
                });

            modelBuilder.Entity("ObligatorioApiario.Models.Apicultor", b =>
                {
                    b.Navigation("Barriles");

                    b.Navigation("Telefonos");

                    b.Navigation("Visitas");
                });

            modelBuilder.Entity("ObligatorioApiario.Models.Barril", b =>
                {
                    b.Navigation("GeneradoPor");
                });

            modelBuilder.Entity("ObligatorioApiario.Models.Colmena", b =>
                {
                    b.Navigation("Instalaciones");

                    b.Navigation("ReinasAsignadas");

                    b.Navigation("TratamientosAplicados");
                });

            modelBuilder.Entity("ObligatorioApiario.Models.Cosecha", b =>
                {
                    b.Navigation("GeneraBarriles");

                    b.Navigation("RealizadaEn");
                });

            modelBuilder.Entity("ObligatorioApiario.Models.Herramienta", b =>
                {
                    b.Navigation("PlanificadasEn");
                });

            modelBuilder.Entity("ObligatorioApiario.Models.Reina", b =>
                {
                    b.Navigation("ColmenasAsignadas");
                });

            modelBuilder.Entity("ObligatorioApiario.Models.Tratamiento", b =>
                {
                    b.Navigation("Aplicaciones");
                });

            modelBuilder.Entity("ObligatorioApiario.Models.Visita", b =>
                {
                    b.Navigation("ApiariosRevisados");

                    b.Navigation("HerramientasPlanificadas");
                });
#pragma warning restore 612, 618
        }
    }
}
